---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.General.ClusterRole.Name }}
rules:
  - apiGroups: [""]
    resources:
      - "persistentvolumeclaims"
      - "persistentvolumes"
      - "events"
    verbs:
      - "patch"
      - "create"
      - "list"
      - "watch"
      - "delete"

  - apiGroups: ["storage.k8s.io"]
    resources:
      - "volumeattachments"
      - "volumeattachments/status"
      - "storageclasses"
      - "csinodes"
    verbs:
      - "patch"
      - "list"
      - "watch"
