---

apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name:  {{ .Values.General.ClusterRoleBinding.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.General.ServiceAccount.Name }}
  namespace: {{ .Values.General.ServiceAccount.NameSpace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.General.ClusterRole.Name }}
  apiGroup: rbac.authorization.k8s.io
