---

apiVersion: v1
kind: Secret
metadata:
  name: secret-csi-config
type: Opaque
data:
  Username: YmFyCg==
  Password: YmFyCg==

---

apiVersion: v1
kind: Secret
metadata:
  name: secret-csi-luks
type: Opaque
data:
  password: YmFyCg==
