---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.LibvirtApi.Secret_name }}
type: Opaque
data:
  Username: {{ .Values.LibvirtApi.Username }}
  Password: {{ .Values.LibvirtApi.Password }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.General.Luks.Secret_name }}
type: Opaque
data:
  password: {{ .Values.General.Luks.Password }}
