apiVersion: v1
kind: Namespace
metadata:
  name: go-space

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  labels:
    app: go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go
        image: mg231223/goapi:latest
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: go-test-service
spec:
  selector:
    app: go
  ports:
    - port: 8080 
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-test-service-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    ingress.class: "haproxy"
spec:
  rules:
  - host: goryszewski.local
    http:
      paths:
        - path: /go
          pathType: Prefix
          backend:
            service:
              name: go-test-service
              port:
                number: 8080