api:
  image: mg231223/apipython:latest
ui:
  image: repo.internal:5000/webui:latest
cj:
  image: repo.internal:5000/backupjob:latest
mysql:
  password: cm9vdAo=
  mysql-pv-claim: ""

general:
  runtimeClassName: isolate
