apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.Id }}-svc-etcd
spec:
  selector:
    component: {{ .Values.Id }}-etcd
  ports:
    - name: clients
      protocol: TCP
      port: 2379
      targetPort: 2379
    - name: peers
      protocol: TCP
      port: 2380
      targetPort: 2380

---

apiVersion: v1
kind: Service
metadata:
  labels:
    type-loadbalancer: ExternalIP
  name:  {{ .Values.Id }}-svc-kube-apiserver
spec:
  type: LoadBalancer
  selector:
    component: {{ .Values.Id }}-kube-apiserver
  ports:
    - protocol: TCP
      port: 6443
      targetPort: 6443
