---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace:  {{ .Values.namespace }}
  name: 2cm-api-python
data:
  redis.yml: |
    service: redis-svc
    port: 6379

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace:  {{ .Values.namespace }}
  name: cp-redis-config 
data:
  redis-config: ''

---