---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-api-python
data:
  redis.yml: |
    service: redis-svc
    port: 6379

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cp-redis-config
data:
  redis-config: ""

---
