apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-sql
spec:
  volumes:
    - name: config
      secret:
        secretName: mysql-root-password
  schedule: "1 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-sql
              image: {{ .Values.cj.image }}
              imagePullPolicy: IfNotPresent
              command:
                - /app/backup-sh.sh
              volumeMounts:
                - name: config
                  readOnly: true
                  mountPath: "/etc/secret-config"
          restartPolicy: Never
      backoffLimit: 4
      activeDeadlineSeconds: 10
