---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python
          image: {{ .Values.api.image }}
          env:
            - name: MYSQL_DB
              value: cloud
            - name: MYSQL_USER
              value: root
            - name: MYSQL_HOST
              value: mysql-svc
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-root-password
                  key: MYSQL_ROOT_PASSWORD

          ports:
            - containerPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-ui-deployment
  labels:
    app: front-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-ui
  template:
    metadata:
      labels:
        app: front-ui
    spec:
      containers:
        - name: front-ui
          image: {{ .Values.ui.image }}
          ports:
            - containerPort: 80

---

