---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
        - name: python-api
          image: {{ .Values.api.image }}
          env:
            - name: FLASK_RUN_HOST
              value: 0.0.0.0
            - name: FLASK_APP
              value: app.py
            - name: MYSQL_DB
              value: cloud
            - name: MYSQL_USER
              value: cloud
            - name: MYSQL_HOST
              value: mysql-svc
            - name: MYSQL_PASS
              value: root

          ports:
            - containerPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-ui-deployment
  labels:
    app: front-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-ui
  template:
    metadata:
      labels:
        app: front-ui
    spec:
      containers:
        - name: front-ui
          image: {{ .Values.ui.image }}
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-svc
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-password
                  key: MYSQL_ROOT_PASSWORD
