# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: drop-default
# spec:
#   podSelector: {}
#   policyTypes:
#     - Ingress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-sql
spec:
  podSelector:
    matchLabels:
      app: mysql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: python-api
      ports:
        - protocol: TCP
          port: 3306
