---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis:latest
      command:
        - redis-server
        - "/redis-master/redis.conf"
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.1"
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: cp-redis-config
        items:
          - key: redis-config
            path: redis.conf

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - image: mysql:5.7
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: cloud
        - name: MYSQL_USER
          value: cloud
        - name: MYSQL_PASSWORD
          value: root
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: mysql-storage
{{ if .Values.mysql.mysqlPvClaim }}
      persistentVolumeClaim:
        claimName: {{ .Values.mysql.mysqlPvClaim }}
{{ else }}
      emptyDir: {}
{{ end }}
    - name: mysql-initdb
      configMap:
        name: sql-init

---

apiVersion: v1
kind: Pod
metadata:
  name: debug-network-pod
spec:
  serviceAccountName: manage-pod
  # automountServiceAccountToken: true
{{ if .Values.general.runtimeClassName }}
  runtimeClassName: {{ .Values.general.runtimeClassName }}
{{ end }}
  volumes:
    - name: cachetoken
      emptyDir: {}
  initContainers:
    - name: authorizer
      image: curlimages/curl
      workingDir: /tmp
      command:
        - curl
        - -X
        - POST
        - http://10.17.3.1:8050/api/v1/auth
        - --data-binary
        - '{"username":$USERNAME,"passowrd":$PASSWORD}'
        - --header
        - "Content-Type: application/json"
        - -o token.json
      env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: apicreds
              key: PASSWORD
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: apicreds
              key: USERNAME
      volumeMounts:
        - mountPath: /tmp
          name: cachetoken

  containers:
    - command:
        - 'sh'
        - '-c'
        - 'while true; do  echo "test"; curl -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt https://kubernetes.default.svc/api/v1/namespaces/{{ .Release.Namespace }}/pods; sleep 5; done'
      image: curlimages/curl
      name: debug-network-container
      volumeMounts:
        - mountPath: /cache
          name: cachetoken
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: 500m
