apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: apicreds
data:
  PASSWORD: {{ .Values.apicreds.password }}
  USERNAME: {{ .Values.apicreds.username }}
